### ISSUE TITLE
Question about controller use in js

### ISSUE THREAD

**Issue by emstans** [banderson5144/sf-react-demo#1]
I have a question -- hopefully issues is the right place to put it.

How are ResponsiveCtrl and its methods being made accessible to the Javascript? When I try to call the actions on either test_react.page or test_demo.page I get this error in the console:

> Uncaught ReferenceError: ResponsiveCtrl is not defined

(for example, line 13 in react-way/actions/index.jsx uses it)

Have I messed something up in the build process or am I missing something entirely? Thanks in advance; this example repo has been useful wrapping my head around this stuff.

**Comment by banderson5144** [comment]
What does your VF Page code look like?

**Comment by emstans** [comment]
Right now my VF pages are identical to the versions in the repo except with bundle.js coming from ngrok.io instead of a static resource.

**Comment by banderson5144** [comment]
I wonder if that could be causing the issue. When you open up Chrome Dev Console, and you start to type Resp, does it auto complete?

**Comment by emstans** [comment]
Oops, I figured it out! The dev org I loaded it into has a namespace defined so I needed to reference [namespace].ReferenceCtrl instead of just ReferenceCtrl. Totally my bad! I'm not super familiar with the Javascript remoting syntax so I thought something else might be afoot.

Thanks for the quick response.

**Comment by banderson5144** [comment]
No problem.
